
title: 75.42 - Taller de programación I
email: tallerdeprogramacion@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Sitio en construcción de la materia 75.42 - Taller de programación, de la facultad
  de ingeniería de la Universidad de Buenos Aires
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# This MUST be on Monday, otherwise _pages/clases.md may not
# yield the correct calendar
current_quater: 2020/09/28

# This MUST be a string of Comma Separated Dates as a Javascript Array
# Don't forget to double quote like:
#   current_quater_holidays: '[]'  # no holidays
#   current_quater_holidays: '["2010/04/13", "2010/05/13"]'  # two holidays
current_quater_holidays: '[]'

github_username:  Taller-de-programacion
repository: Taller-de-Programacion/Taller-de-Programacion.github.io

sercom_url: https://sercom.7542.fi.uba.ar/

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
    style: compressed


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: webjeda-demo

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:

include: [_pages]
version: 0.8

