
title: 75.42 - Taller de programación I
email: tallerdeprogramacion@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Sitio en construcción de la materia 75.42 - Taller de programación, de la facultad
  de ingeniería de la Universidad de Buenos Aires
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

current_quater: 2019/03/12

github_username:  Taller-de-programacion
repository: Taller-de-Programacion/Taller-de-Programacion.github.io

sercom_url: https://sercom.7542.fi.uba.ar/

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
    style: compressed


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlighter: rouge


# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: webjeda-demo

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:

include: [_pages]
version: 0.8

